import streamlit as st
import joblib
import pandas as pd
import plotly.express as px
from datetime import datetime
from huggingface_hub import hf_hub_download # الإضافة الجديدة

st.set_page_config(page_title="SafeDrill AI - Pro Edition", layout="wide")

# --- تعديل تحميل الموديل ليعمل من المستودع الرقمي ---
@st.cache_resource
def load_drilling_model():
    # سيقوم الكود الآن بتحميل الموديل من مستودعك مباشرة
    model_path = hf_hub_download(
        repo_id="Sulaimankudaimi/DigitalOilfield", 
        filename="models/pipe_sticking_model.h5" # أو stuck_pipe_model.pkl حسب الاسم الذي رفعته
    )
    return joblib.load(model_path)

model = load_drilling_model()
# ------------------------------------------------

# Sidebar Branding
with st.sidebar:
    st.image("https://cdn-icons-png.flaticon.com/512/1067/1067357.png", width=80)
    st.markdown("### 🛡️ SafeDrill AI Pro")
    st.markdown(f"**Lead Developer:**\nEng. Sulaiman Kudaimi")
    st.markdown("---")
    # إضافة حقل تكلفة الـ NPT لإبهار المسؤول
    npt_rate = st.number_input("NPT Cost per Hour ($)", value=5000)

# Load Model
@st.cache_resource
def load_drilling_model():
    return joblib.load('stuck_pipe_model.pkl')

model = load_drilling_model()
expected_cols = model.feature_names_in_

st.title("🛡️ Operational Drilling Safety & Advisor")
uploaded_file = st.file_uploader("Upload Drilling Log (CSV)", type=["csv"])

if uploaded_file is not None:
    data = pd.read_csv(uploaded_file)
    data.columns = [c.upper().strip() for c in data.columns]
    
    try:
        X_input = pd.DataFrame()
        X_input['Depth'] = data['DEPTH']
        X_input['Torque'] = data['TORQUE']
        X_input['Hook_Load'] = data['HOOK_LOAD']
        X_input['Pump_Pressure'] = data['PUMP_PRESSURE']
        X_input = X_input[expected_cols]
        
        data['Risk_Score'] = model.predict(X_input)
        risk_percent = (data['Risk_Score'].sum() / len(data)) * 100

        # --- الإضافة رقم 2: AI Action Advisor ---
        st.markdown("### 🤖 AI Technical Advisor")
        if risk_percent > 5:
            st.error(f"🚨 CRITICAL RISK: {risk_percent:.1f}%")
            st.warning("""
            **Recommended Actions:**
            1. **Immediate:** Stop drilling and start circulation.
            2. **Mechanical:** Gradually reduce WOB (Weight on Bit).
            3. **Action:** Monitor Torque trends and reciprocating the pipe slowly.
            """)
        else:
            st.success("✅ Operational Status: STABLE")
            st.info("Advice: Continue drilling as per program. Maintain current ROP.")

        # الرسوم التفاعلية
        col1, col2 = st.columns(2)
        with col1:
            fig_hook = px.line(data, x='HOOK_LOAD', y='DEPTH', title="Hook Load Log", color_discrete_sequence=['blue'])
            fig_hook.update_yaxes(autorange='reversed')
            st.plotly_chart(fig_hook, use_container_width=True)
        with col2:
            fig_torque = px.line(data, x='TORQUE', y='DEPTH', title="Torque Log", color_discrete_sequence=['green'])
            fig_torque.update_yaxes(autorange='reversed')
            st.plotly_chart(fig_torque, use_container_width=True)

        # --- الإضافة رقم 3: ميزة التقرير الفوري ---
        st.markdown("---")
        if st.button("📝 Generate Incident Summary Report"):
            report_time = datetime.now().strftime("%Y-%m-%d %H:%M")
            report_text = f"""
            DRILLING INCIDENT REPORT
            -----------------------
            Date: {report_time}
            Engineer: Sulaiman Kudaimi
            Status: {'CRITICAL' if risk_percent > 5 else 'SAFE'}
            Risk Intensity: {risk_percent:.2f}%
            Max Torque Observed: {data['TORQUE'].max():.2f}
            Min Hook Load Observed: {data['HOOK_LOAD'].min():.2f}
            -----------------------
            Report generated by SafeDrill AI System.
            """
            st.text_area("Report Output (Copy to Clipboard)", report_text, height=200)
            st.download_button("📥 Download Report as TXT", report_text, file_name="Drilling_Report.txt")

    except Exception as e:
        st.error(f"Data processing error: {e}")

st.markdown("---")
st.caption("© 2026 | Eng. Sulaiman Kudaimi | SafeDrill AI Pro v2.0")
